config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :designs do
    member do
      get :new_design
      post :new_design, to: 'tshirts#initialize_cart', as: :initialize_cart
    end
  end
  get :shopping_cart, to: 'orders#shopping_cart', as: :shopping_cart
  resources :items, only: [:index, :create, :destroy]
  resources :orders, only: [:show, :create, :shopping_cart] do
    resources :payments, only: [:new, :create]
  end

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  resources :users, only: [:show]
  match 'users' => 'users#index', :via => :get, :as => :admin_users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'edit_user/:id' => 'users#edit', :via => :get, :as => :admin_edit_user
  match 'update_user/:id' => 'users#update', :via => :patch, :as => :admin_update_user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/design.rb
class Design < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true, length: { maximum: 150 }
  validates :photo, presence: true
  has_many :items
  mount_uploader :photo, PhotoUploader

  def self.tagsArray
    return ['chic', 'mens', 'women', 'business', 'casual', 'funny', 'social', 'aware']
  end
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  # before_action :Design_params, only: [:update]
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index, :show, :new_design]

  def new_design
    @design = Design.find(params[:id])
    authorize @design
    @item = Item.new
    authorize @item
    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    if params[:query].present?
      db_query = "title ILIKE :query OR description ILIKE :query OR tags ILIKE :query"
      @designs = policy_scope(Design.where(db_query, query: "%#{params[:query]}%"))
    else
      @designs = policy_scope(Design)
    end
  end

  def show
    @design = Design.find(params[:id])
    @item = current_order.items.new
    authorize @design
    authorize @item
  end

  def new
    @design = Design.new
    authorize @design
  end

  def create
    @design = Design.new(design_params)
    @design.user = current_user
    authorize @design
    if @design.save
      redirect_to designs_path
    else
      render :new
    end


  end

  def edit
    @design = Design.find(params[:id])
    authorize @design
  end

  def update
    @design = Design.find(params[:id])
    authorize @design
    if @Design.update(design_params)
      redirect_to Design_path(@design)
    else
      render :edit
    end
  end

  def destroy
    @design = Design.find(params[:id])
    authorize @esign
    @design.destroy

    redirect_to designs_path
  end

  private

  def design_params
    params.require(:design).permit(:title, :description, :photo, :query, :tags)
  end
end

app/views/designs/_new_design.html.erb
<div class='modal-header precheckout_modal_header'>
  <h2 class='modal-title precheckout_modal_title' id='myModalLabel'>Your order</h4>
  <button type='button' class='close' data-dismiss='modal'>x</button>
</div>

<div class='modal-body precheckout_modal_body'>
  <%= simple_form_for Item.new do |f| %>

   <table class="precheckout_items_table precheckout_table">
    <thead class="precheckout_items_table_head">
      <tr>
        <th class="line_items_table__heading precheckout_items_table__item--image"></th>
        <th class="line_items_table__heading">Qty</th>
        <th class="line_items_table__heading">Size</th>
        <th class="line_items_table__heading precheckout_items_table__item--price">Price</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="precheckout_items_table__item precheckout_items_table__item--image">
          <img class="image_stack__nav_item_thumb" src="<%= cl_image_path(@design.photo)  %>" alt="">
        </td>
        <td class="precheckout_items_table__item precheckout_items_table__item--qty">
            <%= f.number_field :quantity, value: 1 %>
            <%= f.hidden_field :design_id, value: @design.id %>
        </td>
        <td>
          <div>
            <select>
              <option value="small">S</option>
              <option value="medium">M</option>
              <option value="large">L</option>
            </select>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
<%= f.submit "Add to Cart" %>
<% end %>
</div>

app/views/designs/_new_tshirt.html.erb
<div class='modal-header precheckout_modal_header'>
  <h2 class='modal-title precheckout_modal_title' id='myModalLabel'>Your order</h4>
  <button type='button' class='close' data-dismiss='modal'>x</button>
</div>

<div class='modal-body precheckout_modal_body'>
  <%= simple_form_for Item.new do |f| %>

   <table class="precheckout_items_table precheckout_table">
    <thead class="precheckout_items_table_head">
      <tr>
        <th class="line_items_table__heading precheckout_items_table__item--image"></th>
        <th class="line_items_table__heading">Qty</th>
        <th class="line_items_table__heading">Size</th>
        <th class="line_items_table__heading precheckout_items_table__item--price">Price</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="precheckout_items_table__item precheckout_items_table__item--image">
          <img class="image_stack__nav_item_thumb" src="<%= cl_image_path(@tshirt.photo)  %>" alt="">
        </td>
        <td class="precheckout_items_table__item precheckout_items_table__item--qty">
            <%= f.number_field :quantity, value: 1 %>
            <%= f.hidden_field :design_id, value: @design.id %>
        </td>
        <td>
          <div>
            <select>
              <option value="small">S</option>
              <option value="medium">M</option>
              <option value="large">L</option>
            </select>
          </div>
        </td>
        <td><span><%= @design.price %></span></td>
      </tr>
    </tbody>
  </table>
<%= f.submit "Add to Cart" %>
<% end %>
</div>

app/views/designs/edit.html.erb
<%= simple_form_for(@design) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.submit "Edit the tshirt", class: "btn btn-primary" %>
<% end %>

app/views/designs/index.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-sm-1 col-md-2">
      <div class="facet-menu">
        <ul class="facet-list">
          <h5>Categories</h5>
          <% Design.tagsArray.each do |tag| %>
          <li class="facet-item"><%= link_to tag, designs_path(:query => tag) %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-sm-11 col-md-10">
      <h4>Browse our catalogue from independent artists</h4>
      <div class="row">
        <% @designs.each do |design| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <%= render './components/card', design: design %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/designs/new.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-md">
      <h2>T-Shirt designer</h2>
      <%= simple_form_for(@design) do |f| %>
        <%= f.input :title %>
        <%= f.input :description, as: :text, placeholder: 'Limited to 150 Characters ...', maxlength: 150 %>
        <%= f.input :tags, :hint => 'Add tags separated by commas ","'%>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden  %>
        <%= javascript_pack_tag 'addListener' %>
        <%= f.submit "Save Tee", class: "btn btn-carbon-primary btn-carbon-lg" %>
      <% end %>
      <br>
      <!-- TODO this part of the code can be improved instead of using 1,2,3 we can
      use the white, grey, and black then interpolate the values in the new_design.js -->
      <a href="<%= designs_path %>" class="btn btn-carbon-primary btn-carbon-sm">Back</a>
    </div>
    <div class="col-md">
      <div class="drag-container">
        <div class="draggable" data-controller="photo-swap">
          <img id="user-image", height=225, width=225, src="https://via.placeholder.com/200x200?text=Placeholder">
        </div>
          <img id="imagedest", class="tshirt-image-show", height=550, width=500, src="https://res.cloudinary.com/dju9xcsec/image/upload/v1553144623/White.jpg">
      </div>
    </div>
  </div>
</div>

app/views/designs/new_design.js.erb
document.querySelector('.modal-content').innerHTML = ""
$("#exampleModal").modal('show');
document.querySelector('.modal-content').insertAdjacentHTML('afterbegin', `<%= render "designs/new_design"%>`)

app/views/designs/new_tshirt.js.erb
document.querySelector('.modal-content').innerHTML = ""
$("#exampleModal").modal('show');
document.querySelector('.modal-content').insertAdjacentHTML('afterbegin', `<%= render "designs/new_design"%>`)

app/views/designs/show.html.erb
<br>
<div class="container">
  <div class="design-basic-info">
    <p><% breadcrumb :design, @design %>
      <%= breadcrumbs pretext: "",
                      separator: " &rsaquo; " %>
    </p>
    <h1><%= @design.title %></h1>
  </div>
  <div class="row">
    <div class="col-md">
      <div class="design-overlay">
        <% photoString = @design.photo.url[61..-1] %>
        <% photo = "https://res.cloudinary.com/dju9xcsec/image/upload/l_#{photoString},w_425/v1553144623/White.jpg"%>
        <img class="design-image-show" src="<%= photo %>", height=550, crop: :fill  alt="">
      </div>
    </div>
    <div class="col-md">
      <div class="design-description">
        <h4> Artist: <%= link_to ( @design.user.name || @design.user.email ), user_path(@design.user_id) %></h4>
        <p> Description: <%= @design.description%></p>
      </div>
      <div class="social-media-share-button">
        <%= social_share_button_tag(@design.title , desc: @design.title) %>
      </div>
      <div class="checkout-info">
        <%= link_to 'Add To Cart', new_design_design_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#exampleModal', class: 'btn btn-carbon-primary btn-carbon-lg'} %>
      </div>
      <br>
    </div>
  </div>
  <br>
  <% if @design.user.designs.length > 1 %>
  <h2>More by this artist</h2>
  <div class="row">
    <% @design.user.designs.each do |design| %>
      <% if design != @design %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <%= render './components/card', design: design %>
        </div>
      <% end %>
    <% end %>
  </div>
  <% end %>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>