config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :designs do
    member do
      get :new_design
      post :new_design, to: 'tshirts#initialize_cart', as: :initialize_cart
    end
  end
  get :shopping_cart, to: 'orders#shopping_cart', as: :shopping_cart
  resources :items, only: [:index, :create, :destroy]
  resources :orders, only: [:show, :create, :shopping_cart] do
    resources :payments, only: [:new, :create]
  end

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  resources :users, only: [:show]
  match 'users' => 'users#index', :via => :get, :as => :admin_users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'edit_user/:id' => 'users#edit', :via => :get, :as => :admin_edit_user
  match 'update_user/:id' => 'users#update', :via => :patch, :as => :admin_update_user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :designs, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :services, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :timeoutable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  mount_uploader :photo, PhotoUploader
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
    def index
    @users = policy_scope(User.all).where.not(id: current_user.id)
    authorize @users
    end

    def show
    @user = User.find(params[:id])
    authorize @user
    end

    def destroy
    @user = User.find(params[:id])
    authorize @user
    @user.destroy

    head :no_content
    end

    def update
        if params[:user][:password].blank?
            params[:user].delete(:password)
            params[:user].delete(:password_confirmation)
        end
        @user = User.find(params[:id])
        authorize @user

        if @user.update(user_params)
            render :show
        else
            render_error
        end
    end

    private

    def user_params
    params.require(:user).permit(:id, :password, :password_confirmation, :photo, :email, :photo_cache, :admin)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    service = find_service
    if service.present?
      user = service.user
      success(user)
    else
      user = create_user
      user.valid? ? create_service(user) : display_error
    end
  end

  def google_oauth2
    service = find_service
    if service.present?
      user = service.user
      success(user)
    else
      user = create_user
      user.valid? ? create_service(user) : display_error
    end
  end

  private

  def find_service
    Service.where(provider: auth.provider, uid: auth.uid).first
  end

  def auth
    request.env['omniauth.auth']
  end

  def success(user)
    provider = auth.provider.to_s == 'google_oauth2' ? 'google' : 'facebook'
    sign_in_and_redirect user, event: :authentication
    set_flash_message :notice, :success, kind: provider
  end

  def display_error
    flash[:error] = "Are you trying to login with a different provider than you signed up with?"
    redirect_to new_user_session_path
  end

  def create_user
    User.create(
      email: auth.info.email,
      password: Devise.friendly_token[0, 20]
    )
  end

  def create_service(user)
    user.services.create!(
      provider: auth.provider,
      uid: auth.uid,
      expires_at: Time.at(auth.credentials.expires_at),
      access_token: auth.credentials.token
    )

    success(user)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:photo, :first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:photo, :first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end

  protected

  # lets not delete this line this time - it redirects the user after update

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
class SessionsController < Devise::SessionsController
  respond_to :json

  private

  def respond_with(resource, _opts = {})
    render json: resource
  end

  def respond_to_on_destroy
    head :no_content
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  def index
    @users = policy_scope(User.all).where.not(id: current_user.id)
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def destroy
    @user = User.find(params[:id])
    authorize @user
    @user.destroy

    redirect_to admin_users_path
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    @user = User.find(params[:id])
    authorize @user

    @user.update(user_params)
    flash[:notice] = "Successfully updated user"
    redirect_to user_path(@user)
  end

    private

  def user_params
    params.require(:user).permit(:id, :password, :password_confirmation, :photo, :email, :photo_cache, :admin)
  end
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <h2>Edit <%= @user.email %></h2>

      <%= simple_form_for(@user, url: admin_update_user_path(@user), html: { method: :patch }) do |f| %>

        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :email, required: true, autofocus: true %>
          <%= f.input :password,
                      hint: "leave it blank if you don't want to change it",
                      required: false,
                      input_html: { autocomplete: "new-password" } %>
          <%= f.input :password_confirmation,
                      required: false,
                      input_html: { autocomplete: "new-password" } %>
          <%= f.input :current_password,
                      hint: "we need your current password to confirm your changes",
                      required: true,
                      input_html: { autocomplete: "current-password" } %>
          <%= f.input :admin  %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Update" %>
        </div>
      <% end %>

      <h3>Cancel my account</h3>

      <p>Unhappy? <%= link_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete %></p>


      <%= link_to "Back", :back %>
          </div>
        </div>

</div>

app/views/users/index.html.erb
<div class="container">
  <div class="list-group text-center">
    <h1>Admin Panel Users</h1>

    <% @users.each do |each| %>
    <li class="list-group-item">
      <%= link_to each.email, user_path(each) %>
        <% if current_user == each || current_user.admin %>
          <%= link_to "Edit", admin_edit_user_path(each) %>
          <%= link_to "Delete", admin_destroy_user_path(each), method: :delete %>
        <% end %>
    </li>

    <% end %>
  </div>

</div>

app/views/users/show.html.erb
<div class="banner user-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 5%, rgba(10,10,10,0.6) 5%), url('https://source.unsplash.com/GZMjMukr5zU')">

  <div class="user-banner-content">

   <% if @user.photo.present? %>
     <img class="avatar-lg user-avatar" src="<%= cl_image_path(@user.photo)%>" alt="">
   <% else %>
     <img class="avatar-lg user-avatar" src="<%= asset_path('avatar.png')%>" alt="">
   <% end %>
    <h1><%= @user.name %></h1>
  </div>

</div>
<br>
<div class="container">
  <div class="row">
    <div class="col-md user-right-align">
      <div class="user-social-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>
    </div>
  </div>
  <br>
  <h2>About <%= @user.name %></h2>
  <div class="user-content">
    <p> <%= @user.bio %> </p>
  </div>
  <br>
  <br>
  <h2>Artist Collection</h2>
  <div class="row">
    <% @user.designs.each do |design| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= render './components/card', design: design %>
      </div>
    <% end %>
  </div>
</div>