config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :designs do
    member do
      get :new_design
      post :new_design, to: 'tshirts#initialize_cart', as: :initialize_cart
    end
  end
  get :shopping_cart, to: 'orders#shopping_cart', as: :shopping_cart
  resources :items, only: [:index, :create, :destroy]
  resources :orders, only: [:show, :create, :shopping_cart] do
    resources :payments, only: [:new, :create]
  end

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  resources :users, only: [:show]
  match 'users' => 'users#index', :via => :get, :as => :admin_users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'edit_user/:id' => 'users#edit', :via => :get, :as => :admin_edit_user
  match 'update_user/:id' => 'users#update', :via => :patch, :as => :admin_update_user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/rentals/show.html.erb
<h2>Checkout</h2>

<% if @items.any? %>
  <% @items.each do |item| %>
  <p><%= item.tshirt.name %> | <% link_to "Delete", item_path(item), :data => {:confirm => "Fight!", :method => "delete"} %></p>
  <p>Unit Price: <%= number_to_currency item.tshirt.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.tshirt.price * item.quantity) %></p>
  <% end %>
  <p>Your Total: <%= number_to_currency current_order.total %></p>
  <% else %>
  <p>Your shopping cart is empty.</p>
  <% end %>

  <%= link_to "Pay", tshirts_path %>